### ISSUE TITLE
config file is incorrectly updated

### ISSUE THREAD

**Issue by hrafnthor** [hrafnthor/ansible-samba#2]
Multiple runs with the same inputs will create invalid config files.

### Description

The following host file configuration will create a correct Samba config file on first run:

```yaml
samba:
  remove: false
  users:
    - name: hrafn
      password_var: samba_user_hrafn_password
  shares:
    - label: hrafn
      remove: false
      path: "/home/hrafn/public"
      comment: "Public directory on Kite"
      browsable: true
      writable: true
      read_only: false
      quests: false
      users:
        - hrafn
```

Results in:

```ini
[hrafn]
path = /home/hrafn/public
writable = yes
read only = no
browsable = yes
valid users = @hrafn
```

A second run, without any input changes, will results in a flawed config file:

```ini
[hrafn]
path = /home/hrafn/public
writable = yes
read only = no
browsable = yes
[hrafn]
valid users = @hrafn
```
